#!/usr/bin/env bash

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT"

fail() {
  echo "::error::$1" >&2
  exit 1
}

for file in PRIVACY.md TERMS.md SECURITY.md docs/DATA_FLOW_INVENTORY.md docs/GITHUB_REPOSITORY_CONTROLS.md docs/INTERFACE_CONTRACT.md docs/LEGAL_RELEASE_CHECKLIST.md docs/BRAND_ASSET_REVIEW.md docs/COMMERCIAL_LICENSE_SECURITY.md docs/codex-integration-field-notes.md docs/manus-api-field-notes.md; do
  test -s "$file" || fail "Missing canonical legal/data-flow artifact: $file"
done

repository_bash_count="$(rg --files scripts -g '*.sh' | wc -l | tr -d '[:space:]')"
repository_ruby_count="$(rg --files scripts -g '*.rb' | wc -l | tr -d '[:space:]')"
repository_swift_count="$(rg --files scripts -g '*.swift' | wc -l | tr -d '[:space:]')"
for repository_script_count in \
  "$repository_bash_count" \
  "$repository_ruby_count" \
  "$repository_swift_count"; do
  [[ "$repository_script_count" =~ ^[1-9][0-9]*$ ]] \
    || fail "Repository script inventory could not be enumerated"
done

require_documented() {
  local pattern="$1"
  local file="$2"
  local label="$3"
  rg -q "$pattern" "$file" || fail "$label is missing from $file"
}

require_documented '127\.0\.0\.1' PRIVACY.md "Local Hook boundary"
require_documented 'api\.manus\.im' PRIVACY.md "Manus third-party flow"
require_documented 'tasks\.sqlite' PRIVACY.md "Local task persistence"
require_documented 'View History' PRIVACY.md "Local history viewing control"
require_documented 'Disconnect All' PRIVACY.md "Bulk local-Hook removal control"
require_documented 'ExitPlanMode' PRIVACY.md "Claude plan-review local processing"
require_documented 'Keychain' PRIVACY.md "API-key storage"
require_documented 'GitHub Releases' PRIVACY.md "Update destination"
require_documented '[Ss]ystem profil' PRIVACY.md "Sparkle profiling behavior"
require_documented 'Notification Center' PRIVACY.md "Notification content flow"
require_documented 'clipboard' PRIVACY.md "User-initiated diagnostics flow"
require_documented 'Cloudflare' PRIVACY.md "Realtime tunnel state"
require_documented 'Local Usage Insights' PRIVACY.md "Opt-in local usage processing"
require_documented 'token_count' PRIVACY.md "Codex usage source"
require_documented 'Qwen Code' PRIVACY.md "Qwen Code local Hook processing"
require_documented 'GitHub Copilot CLI' PRIVACY.md "Copilot CLI local Hook processing"
require_documented 'Kimi Code CLI' PRIVACY.md "Kimi Code CLI local Hook processing"
require_documented 'startup window' PRIVACY.md "Previous-launch readiness health"
require_documented 'does not inspect a crash report' PRIVACY.md "No local crash-report inspection"
require_documented 'raw error descriptions' PRIVACY.md "Unified-log raw-error exclusion"
require_documented 'short-lived OpenAI-signed Codex App Server' PRIVACY.md "Codex Hook trust metadata processing"
require_documented '`hooks/list`' PRIVACY.md "Codex Hook trust protocol disclosure"
require_documented '5,000' PRIVACY.md "Finite local task-history retention"
require_documented '20,000' PRIVACY.md "Finite local progress-history retention"
require_documented 'text is materialized in the app' PRIVACY.md "Persisted-row pre-materialization boundary"
require_documented '`0700`' PRIVACY.md "Private local-history directory permissions"
require_documented '`0600`' PRIVACY.md "Private local-history file permissions"
require_documented 'rejects links, non-regular files' PRIVACY.md "Local-history link/type boundary"
require_documented 'anchors for both the final folder and main file' PRIVACY.md "Local-history directory and file anchors"
require_documented 'before and after every history' PRIVACY.md "Runtime SQLite operation boundary"
require_documented 'full SQLite Connection lifetime' PRIVACY.md "Runtime SQLite anchor lifetime"
require_documented 'at most 4 MiB' PRIVACY.md "Managed Hook config read bound"
require_documented 'symbolic links, hard links' PRIVACY.md "Managed Hook link boundary"
require_documented 'New configuration files use mode `0600`' PRIVACY.md "Managed Hook private creation mode"

require_documented 'MIT License' TERMS.md "Repository license relationship"
require_documented 'third-part' TERMS.md "Third-party service terms"
require_documented 'Agent actions' TERMS.md "Agent approval risk"
require_documented 'trial' TERMS.md "Commercial status"
require_documented 'zero trust anchors' docs/COMMERCIAL_LICENSE_SECURITY.md "Disabled commercial trust state"
require_documented 'no customer PII' docs/COMMERCIAL_LICENSE_SECURITY.md "Privacy-minimal license schema"
require_documented 'all nine Agent marks' docs/BRAND_ASSET_REVIEW.md "Complete Agent brand review boundary"
require_documented 'provenanceReview: reviewed' docs/BRAND_ASSET_REVIEW.md "Brand provenance release requirement"
require_documented 'trademarkReview: approved' docs/BRAND_ASSET_REVIEW.md "Brand trademark release requirement"
require_documented 'not legal advice' docs/BRAND_ASSET_REVIEW.md "Brand review legal limitation"
require_documented 'fails before loading Release credentials' docs/LEGAL_RELEASE_CHECKLIST.md "Fail-closed commercial brand review gate"

for source_fact in \
  '127\.0\.0\.1' \
  'api\.manus\.im' \
  'tasks\.sqlite' \
  'manus_api_key' \
  'Cloudflare' \
  'Sparkle' \
  'Notification Center' \
  'Copy / Save Diagnostics'; do
  require_documented "$source_fact" docs/DATA_FLOW_INVENTORY.md "Known data flow: $source_fact"
done
require_documented 'ManagedConfigFile' docs/DATA_FLOW_INVENTORY.md "Managed Hook transaction source map"
require_documented 'Local Agent Hook request authorization' docs/DATA_FLOW_INVENTORY.md "Local Hook request-authorization data flow"
require_documented 'X-Dev-Island-Hook: v1' docs/DATA_FLOW_INVENTORY.md "Local Hook non-simple request marker"
require_documented '256-bit random `X-Dev-Island-Authorization`' docs/DATA_FLOW_INVENTORY.md "Local Hook cross-user credential"
require_documented 'local-hook-authorization\.header' docs/DATA_FLOW_INVENTORY.md "Local Hook private credential file"
require_documented 'never enters Agent config, plugin source, argv, logs, SQLite or diagnostics' docs/DATA_FLOW_INVENTORY.md "Local Hook credential non-disclosure"
require_documented '256-bit random authorization' PRIVACY.md "Local Hook authorization privacy disclosure"
require_documented 'local-hook-authorization\.header' PRIVACY.md "Local Hook authorization persistence disclosure"

require_documented 'CommercialLicenseVerifier' docs/DATA_FLOW_INVENTORY.md "Commercial license data-flow state"
require_documented 'Local single-instance launch arbitration' docs/DATA_FLOW_INVENTORY.md "Single-instance launch data flow"
require_documented 'For at most 32 same-Bundle candidates' docs/DATA_FLOW_INVENTORY.md "Bounded single-instance candidate set"
require_documented 'reads Bundle ID, positive PID and termination state' docs/DATA_FLOW_INVENTORY.md "Minimal single-instance process metadata"
require_documented 'Security\.framework to validate the dynamic PID' docs/DATA_FLOW_INVENTORY.md "Dynamic-PID code-signature validation"
require_documented 'exact signing identifier, signature flags, runtime Mach-O slice CDHash and optional Team ID' docs/DATA_FLOW_INVENTORY.md "Bounded single-instance signing identity"
require_documented 'Non-ad-hoc Team identity must pass an Apple-generic anchor' docs/DATA_FLOW_INVENTORY.md "Apple-anchored Team identity boundary"
require_documented 'runtime Mach-O slice CDHash' docs/DATA_FLOW_INVENTORY.md "Runtime-slice ad-hoc CDHash identity"
require_documented 'only a signature explicitly flagged ad-hoc may use the exact same runtime-slice CDHash rule' docs/DATA_FLOW_INVENTORY.md "Explicit ad-hoc slice-CDHash boundary"
require_documented 'Native arm64 and Rosetta x86_64 CDHashes differ and do not trust one another' docs/DATA_FLOW_INVENTORY.md "Mixed-architecture ad-hoc fail-open boundary"
require_documented 'lowest older trusted PID is revalidated immediately before AppKit activates' docs/DATA_FLOW_INVENTORY.md "Single-instance winner revalidation"
require_documented 'missing identity, overload, drift, vanished winner or activation failure keeps the current App running' docs/DATA_FLOW_INVENTORY.md "Single-instance fail-open boundary"
require_documented 'Bundle ID is only a candidate filter, never identity' docs/DATA_FLOW_INVENTORY.md "Bundle ID is not a code identity"
require_documented 'neither logged nor added to diagnostics' docs/DATA_FLOW_INVENTORY.md "Single-instance identity non-persistence"
require_documented 'No IPC payload or network destination exists' docs/DATA_FLOW_INVENTORY.md "Single-instance local-only data flow"
require_documented 'SwiftUI root Settings Scene must remain inert until arbitration finishes' docs/DATA_FLOW_INVENTORY.md "Pre-gate root Scene must stay inert"
require_documented 'must not construct a TaskStore-backed SettingsView before the gate' docs/DATA_FLOW_INVENTORY.md "Pre-gate SettingsView construction forbidden"
require_documented '`CFFIXED_USER_HOME` does not isolate the login Keychain' docs/DATA_FLOW_INVENTORY.md "Ordinary live owner Keychain limitation"
require_documented 'ordinary listener-owning live run must not be described as hermetic' docs/DATA_FLOW_INVENTORY.md "Ordinary live owner is not hermetic"
require_documented '`single-instance-identity-v2-20260831` artifact is rejected because its pre-gate SwiftUI Scene could construct TaskStore-backed Settings content' docs/DATA_FLOW_INVENTORY.md "Rejected v2 pre-gate Scene evidence"
require_documented 'authoritative `single-instance-identity-v3-20260831` artifact' docs/DATA_FLOW_INVENTORY.md "Accepted corrected single-instance artifact"
require_documented '20/20 same-native-arm64-slice ad-hoc copies yielded' docs/DATA_FLOW_INVENTORY.md "Corrected artifact live matrix"
require_documented '231 / 235\.5 / 302 / 1155 ms' docs/DATA_FLOW_INVENTORY.md "Single-instance process arbitration timing"
require_documented 'CommercialLicenseDocumentStore' docs/DATA_FLOW_INVENTORY.md "Commercial license storage source map"
require_documented 'CommercialLicenseActivation' docs/DATA_FLOW_INVENTORY.md "Commercial activation source map"
require_documented 'uninstantiated HTTPS transport' docs/DATA_FLOW_INVENTORY.md "Disabled commercial HTTPS transport data flow"
require_documented 'no public initializer or factory' docs/DATA_FLOW_INVENTORY.md "Commercial HTTPS endpoint construction remains module-internal"
require_documented 'Response bytes stop at 32 KiB while reading' docs/DATA_FLOW_INVENTORY.md "Commercial HTTPS streaming response bound"
require_documented 'underlying URLSession work' docs/DATA_FLOW_INVENTORY.md "Commercial HTTPS cancellation reaches URLSession work"
require_documented 'No configured shipping destination' docs/DATA_FLOW_INVENTORY.md "Commercial HTTPS destination remains unconfigured"
require_documented 'Maintainer commercial-activation loopback sandbox' docs/DATA_FLOW_INVENTORY.md "Commercial activation loopback test data flow"
require_documented 'not provider sandbox, production HTTPS/streaming/cancellation, checkout' docs/DATA_FLOW_INVENTORY.md "Commercial loopback evidence limitation"
require_documented '16–128 byte activation code' docs/DATA_FLOW_INVENTORY.md "Commercial activation code boundary"
require_documented 'erased with `memset_s`' docs/DATA_FLOW_INVENTORY.md "Commercial activation secret-memory lifecycle"
require_documented 'commercial_license_v1' docs/DATA_FLOW_INVENTORY.md "Commercial license Keychain account"
require_documented 'WhenUnlockedThisDeviceOnly' docs/DATA_FLOW_INVENTORY.md "Commercial license device-only accessibility"
require_documented 'non-synchronizable' docs/DATA_FLOW_INVENTORY.md "Commercial license non-sync behavior"
require_documented 'View History' docs/DATA_FLOW_INVENTORY.md "Local history viewing data flow"
require_documented '128 live sessions' docs/DATA_FLOW_INVENTORY.md "Per-connector live-session bound"
require_documented 'newest 5,000 task rows' docs/DATA_FLOW_INVENTORY.md "Finite local task-history data flow"
require_documented '20,000 progress rows' docs/DATA_FLOW_INVENTORY.md "Finite local progress-history data flow"
require_documented 'before SQLite\.swift materializes text' docs/DATA_FLOW_INVENTORY.md "Persisted-row read boundary"
require_documented 'owner-only `0700`' docs/DATA_FLOW_INVENTORY.md "Private SQLite directory data flow"
require_documented 'owner-only `0600`' docs/DATA_FLOW_INVENTORY.md "Private SQLite file data flow"
require_documented 'anchor both final-directory and main-file' docs/DATA_FLOW_INVENTORY.md "SQLite directory and file identity anchors"
require_documented 'full Connection lifetime' docs/DATA_FLOW_INVENTORY.md "Runtime SQLite anchor lifetime"
require_documented 'before and after every history read, write, retention pass' docs/DATA_FLOW_INVENTORY.md "Runtime SQLite operation boundary"
require_documented 'terminally disables the active history-store instance' docs/DATA_FLOW_INVENTORY.md "Runtime SQLite terminal-failure behavior"
require_documented 'Disconnect All' docs/DATA_FLOW_INVENTORY.md "Bulk local-Hook removal data flow"
require_documented 'ExitPlanMode' docs/DATA_FLOW_INVENTORY.md "Claude plan-review data flow"
require_documented 'Local Codex usage insight' docs/DATA_FLOW_INVENTORY.md "Opt-in local usage data flow"
require_documented 'Qwen Code lifecycle and permission hooks' docs/DATA_FLOW_INVENTORY.md "Qwen Code Preview data flow"
require_documented 'GitHub Copilot CLI lifecycle and attention hooks' docs/DATA_FLOW_INVENTORY.md "Copilot CLI Preview data flow"
require_documented 'Kimi Code CLI lifecycle and approval-attention hooks' docs/DATA_FLOW_INVENTORY.md "Kimi Code CLI Preview data flow"
require_documented 'Previous launch health' docs/DATA_FLOW_INVENTORY.md "Local launch-health data flow"
require_documented 'devIsland\.launchHealth\.didStart' docs/DATA_FLOW_INVENTORY.md "Launch-health start marker"
require_documented 'devIsland\.launchHealth\.startupReady' docs/DATA_FLOW_INVENTORY.md "Launch-health ready marker"
require_documented 'devIsland\.launchHealth\.schemaVersion' docs/DATA_FLOW_INVENTORY.md "Launch-health schema marker"
require_documented 'devIsland\.launchHealth\.consecutiveStartupInterruptions' docs/DATA_FLOW_INVENTORY.md "Launch-health bounded count"
require_documented 'devIsland\.launchHealth\.cleanExit.*migration-only' docs/DATA_FLOW_INVENTORY.md "Launch-health legacy migration boundary"
require_documented 'raw error descriptions are prohibited by CI' docs/DATA_FLOW_INVENTORY.md "Unified-log privacy gate"
require_documented 'Configured' docs/DATA_FLOW_INVENTORY.md "Codex config-versus-trust boundary"
require_documented 'Codex Hook trust verification' docs/DATA_FLOW_INVENTORY.md "Codex trust-probe data flow"
require_documented '2 MiB' docs/DATA_FLOW_INVENTORY.md "Codex trust-probe response bound"
require_documented 'OpenAI-signed `com.openai.codex`' docs/DATA_FLOW_INVENTORY.md "Codex trust-probe binary origin"
require_documented 'review-and-trust-hooks' docs/codex-integration-field-notes.md "Official Codex Hook trust source"
require_documented '`hooks/list`' docs/codex-integration-field-notes.md "Documented Codex App Server option"
require_documented 'Shipping bounded App Server trust probe' docs/codex-integration-field-notes.md "Shipping Codex trust-probe boundary"
require_documented 'No public API was found' docs/codex-integration-field-notes.md "Unsupported Codex Cloud monitoring boundary"

require_documented '版本: v6\.90\.0' docs/INTERFACE_CONTRACT.md "Current interface-contract version"
require_documented '可信代码身份单实例接管' docs/INTERFACE_CONTRACT.md "Trusted single-instance launch contract"
require_documented 'Security\.framework 由动态 PID 解析有效代码签名' docs/INTERFACE_CONTRACT.md "Dynamic-PID identity contract"
require_documented 'anchor apple generic' docs/INTERFACE_CONTRACT.md "Apple-anchored Team contract"
require_documented '只有 signing flags 明确标记为 ad-hoc' docs/INTERFACE_CONTRACT.md "Explicit ad-hoc identity contract"
require_documented 'root `Settings` Scene 必须在 gate 前保持 inert' docs/INTERFACE_CONTRACT.md "Root Settings Scene inertness contract"
require_documented '不得构造绑定 `TaskStore\.shared` 的' docs/INTERFACE_CONTRACT.md "Pre-gate TaskStore-backed SettingsView prohibition"
require_documented '当前实际运行的 Mach-O slice' docs/INTERFACE_CONTRACT.md "Runtime Mach-O slice identity contract"
require_documented 'native arm64 与 Rosetta x86_64' docs/INTERFACE_CONTRACT.md "Native and Rosetta identity separation"
require_documented '同 Bundle 候选最多 32 个，超限直接 fail open' docs/INTERFACE_CONTRACT.md "Bounded single-instance fail-open contract"
require_documented '最低正 PID' docs/INTERFACE_CONTRACT.md "Deterministic single-instance winner"
require_documented '同一 PID 再解析一次代码身份' docs/INTERFACE_CONTRACT.md "Single-instance PID revalidation contract"
require_documented '进程消失、PID reuse 或身份漂移' docs/INTERFACE_CONTRACT.md "Single-instance identity-race contract"
require_documented 'AppKit 成功激活精确、二次验证后的 winner' docs/INTERFACE_CONTRACT.md "Activation-after-revalidation contract"
require_documented 'winner 消失或激活失败时继续启动' docs/INTERFACE_CONTRACT.md "Single-instance activation fail-open contract"
require_documented '精确参数\+环境双重 opt-in 必须绕过单实例 gate' docs/INTERFACE_CONTRACT.md "Hermetic single-instance bypass"
require_documented '`CFFIXED_USER_HOME` 不隔离当前用户的 login Keychain' docs/INTERFACE_CONTRACT.md "Ordinary live owner does not isolate login Keychain"
require_documented '不得称为 hermetic 或用来证明 Keychain/网络零访问' docs/INTERFACE_CONTRACT.md "Ordinary live owner evidence limitation"
require_documented 'artifact 因 root Settings Scene 在 gate 前可能构造' docs/INTERFACE_CONTRACT.md "Rejected v2 pre-gate Scene artifact"
require_documented 'Security\.framework must validate each dynamic PID' docs/CI_DIAGNOSTICS.md "Dynamic-PID diagnostic boundary"
require_documented 'only explicitly ad-hoc QA copies may use the same nonempty' docs/CI_DIAGNOSTICS.md "Ad-hoc CDHash diagnostic boundary"
require_documented 'native arm64 and Rosetta x86_64' docs/CI_DIAGNOSTICS.md "Mixed-architecture diagnostic boundary"
require_documented 'more than 32 candidates and every' docs/CI_DIAGNOSTICS.md "Candidate-overload diagnostic boundary"
require_documented 'resolution failure stay fail-open' docs/CI_DIAGNOSTICS.md "Identity-resolution fail-open diagnostic"
require_documented 'lowest older trusted PID is re-resolved' docs/CI_DIAGNOSTICS.md "Winner revalidation diagnostic"
require_documented 'SwiftUI root Settings Scene must remain inert before the gate' docs/CI_DIAGNOSTICS.md "Root Scene diagnostic boundary"
require_documented 'construct a TaskStore-backed SettingsView' docs/CI_DIAGNOSTICS.md "Pre-gate SettingsView diagnostic boundary"
require_documented '`single-instance-identity-v2-20260831` artifact is' docs/CI_DIAGNOSTICS.md "Rejected v2 artifact identity"
require_documented 'rejected for this pre-gate Scene risk' docs/CI_DIAGNOSTICS.md "Rejected v2 diagnostic classification"
require_documented '`single-instance-identity-v3-20260831` artifact is the' docs/CI_DIAGNOSTICS.md "Authoritative v3 diagnostic artifact"
require_documented '20/20 native-arm64 ad-hoc live matrix' docs/CI_DIAGNOSTICS.md "Authoritative v3 live matrix"
require_documented 'not expose the duplicate.*true exit status' docs/CI_DIAGNOSTICS.md "LaunchServices exit-status limitation"
require_documented '`CFFIXED_USER_HOME` does not isolate' docs/CI_DIAGNOSTICS.md "Ordinary live owner Keychain diagnostic limitation"
require_documented 'Such a run is ordinary-live, not hermetic' docs/CI_DIAGNOSTICS.md "Ordinary live owner diagnostic classification"
require_documented '商业激活 pre-provider loopback sandbox' docs/INTERFACE_CONTRACT.md "Commercial activation loopback sandbox contract"
require_documented '不验证 TLS、一次性兑换、重放/枚举防护' docs/INTERFACE_CONTRACT.md "Commercial activation loopback limitation contract"
require_documented '商业激活 transport 失败关闭矩阵' docs/INTERFACE_CONTRACT.md "Commercial activation failure-matrix contract"
require_documented '3xx.*redirect target 零请求' docs/INTERFACE_CONTRACT.md "Commercial activation no-redirect contract"
require_documented 'production transport 必须在读取期间限制 response bytes' docs/INTERFACE_CONTRACT.md "Commercial activation streaming-bound limitation"
require_documented 'HTTPS transport 约定（v6.81）' docs/INTERFACE_CONTRACT.md "Commercial activation HTTPS interface contract"
require_documented '第 32 KiB\+1 字节到达前失败' docs/INTERFACE_CONTRACT.md "Commercial activation live streaming byte limit"
require_documented 'App/AppLib 不得构造' docs/INTERFACE_CONTRACT.md "Commercial HTTPS transport remains disconnected"
require_documented 'v6.82 endpoint construction / cancellation' docs/INTERFACE_CONTRACT.md "Commercial HTTPS endpoint capability and cancellation contract"
require_documented '不得暴露 `public init` 或 `public static func`' docs/INTERFACE_CONTRACT.md "Commercial HTTPS endpoint construction is not public"
require_documented '观察其底层 `stopLoading`' docs/INTERFACE_CONTRACT.md "Commercial HTTPS underlying request cancellation evidence"
require_documented 'exposes neither a public initializer nor public factory' docs/CI_DIAGNOSTICS.md "Commercial HTTPS public-construction diagnostic boundary"
require_documented 'waits for URLProtocol `stopLoading`' docs/CI_DIAGNOSTICS.md "Commercial HTTPS underlying cancellation diagnostic evidence"
require_documented '真实 HTTP operation ownership 矩阵' docs/INTERFACE_CONTRACT.md "Commercial activation operation-ownership contract"
require_documented '签名 response 确实返回后仍得到' docs/INTERFACE_CONTRACT.md "Commercial activation late-response cancellation contract"
require_documented '只有新 operation 能进入 verify-before-save' docs/INTERFACE_CONTRACT.md "Commercial activation latest-operation commit contract"
require_documented 'pre-cancelled zero-ownership 边界' docs/INTERFACE_CONTRACT.md "Commercial activation pre-cancelled ownership contract"
require_documented '不得先 invalidate/supersede 当前 pending operation' docs/INTERFACE_CONTRACT.md "Commercial activation pre-cancelled non-displacement contract"
require_documented 'pre-cancelled second call sends zero additional requests' docs/DATA_FLOW_INVENTORY.md "Commercial activation pre-cancelled zero-request data flow"
require_documented 'Manus 签名窗口重放与终态单调性' docs/INTERFACE_CONTRACT.md "Manus replay-window contract"
require_documented 'Manus replay 真实 HTTP transport 回归' docs/INTERFACE_CONTRACT.md "Manus replay live-HTTP test contract"
require_documented 'Production 公开构造必须始终使用固定 1,024' docs/INTERFACE_CONTRACT.md "Manus production replay capacity contract"
require_documented '1,024 个仍在有效签名窗口内的 ID' docs/INTERFACE_CONTRACT.md "Manus replay capacity contract"
require_documented 'HTTP 503' docs/INTERFACE_CONTRACT.md "Manus replay saturation response contract"
require_documented 'Manus Webhook trust generation 与 cleanup transaction（v6\.85\.0）' docs/INTERFACE_CONTRACT.md "Manus v6.85 transaction contract"
require_documented 'exact external URL \+ canonical RSA public-key identity' docs/INTERFACE_CONTRACT.md "Canonical Manus trust-generation tuple"
require_documented '至少 2,048-bit' docs/INTERFACE_CONTRACT.md "Minimum Manus RSA key strength"
require_documented 'staleTrustGeneration.*HTTP 401' docs/INTERFACE_CONTRACT.md "Stale Manus trust-generation rejection"
require_documented '`webhookRecoveryStateV1` envelope' docs/INTERFACE_CONTRACT.md "Atomic Manus recovery envelope"
require_documented '`WebhookDeletionOperation`' docs/INTERFACE_CONTRACT.md "Shared per-ID Manus deletion ownership"
require_documented 'response\.ok == true' docs/INTERFACE_CONTRACT.md "Explicit Manus deletion confirmation"
require_documented 'GET /v2/webhook\.list' docs/INTERFACE_CONTRACT.md "Official Manus webhook.list recovery endpoint"
require_documented 'active.*exact callback digest.*startedAt ± 300s' docs/INTERFACE_CONTRACT.md "Active exact-digest Manus recovery window"
require_documented '同一 digest 若对应多个本地 unresolved attempt.*归属有歧义' docs/INTERFACE_CONTRACT.md "Ambiguous Manus recovery fails closed"
require_documented 'discoveredWebhookIDs.*跨进程保留' docs/INTERFACE_CONTRACT.md "Bound discovered-ID retry contract"
require_documented '404.*not_found' docs/INTERFACE_CONTRACT.md "Idempotent Manus not-found deletion contract"
require_documented 'terminal gate：known' docs/INTERFACE_CONTRACT.md "Complete Manus stop terminal gate"
require_documented 'launch、deletion 与 listing ownership' docs/INTERFACE_CONTRACT.md "Manus stop operation-ownership terminal gate"
require_documented '`webhookCleanupFailed`' docs/INTERFACE_CONTRACT.md "Recoverable Manus cleanup failure"
require_documented 'delete-before-credential-release' docs/INTERFACE_CONTRACT.md "Manus credential-release ordering"
require_documented 'Remote callback cleanup pending; retry disconnect' docs/INTERFACE_CONTRACT.md "Recoverable Manus cleanup state"
require_documented '`CleanupOnlyWebhookServer`' docs/INTERFACE_CONTRACT.md "Polling-only Manus cleanup owner"
require_documented 'liveV2AcceptanceComplete.*`false`' docs/INTERFACE_CONTRACT.md "Manus realtime remains release-disabled"
require_documented 'replay window containing at most 1,024' PRIVACY.md "English Manus replay-window disclosure"
require_documented '最多 1,024 个有限 event ID' PRIVACY.md "Chinese Manus replay-window disclosure"
require_documented 'full live replay window returns 503' docs/DATA_FLOW_INVENTORY.md "Manus replay saturation data flow"
require_documented 'Completed/Failed cannot regress to Waiting' docs/DATA_FLOW_INVENTORY.md "Manus terminal-state data flow"
require_documented 'Keychain credential is intentionally retained' docs/DATA_FLOW_INVENTORY.md "Manus cleanup credential retention data flow"
require_documented 'joins any in-flight Disconnect removal' docs/DATA_FLOW_INVENTORY.md "Manus Connect/Disconnect ownership data flow"
require_documented 'old manager must use the old credential' docs/DATA_FLOW_INVENTORY.md "Manus replacement-key cleanup ordering"
require_documented 'cleanup-only manager that shares the authoritative shipping `webhookRecoveryStateV1` envelope' docs/DATA_FLOW_INVENTORY.md "Polling-only Manus recovery-envelope data flow"
require_documented 'one or more bounded accepted webhook IDs pending deletion' docs/DATA_FLOW_INVENTORY.md "Multi-ID Manus cleanup data flow"
require_documented 'at-least-2,048-bit RSA public key' docs/DATA_FLOW_INVENTORY.md "Manus RSA-strength data flow"
require_documented 'canonical key identity and private trust-generation token' docs/DATA_FLOW_INVENTORY.md "Canonical Manus trust-generation state"
require_documented 'Replay generation is exact external URL \+ canonical RSA public-key identity' docs/DATA_FLOW_INVENTORY.md "Manus replay-generation data flow"
require_documented 'request authenticated before rotation returns 401' docs/DATA_FLOW_INVENTORY.md "Stale Manus request data flow"
require_documented 'Each launch owns its concrete process before `process\.start\(\)`' docs/DATA_FLOW_INVENTORY.md "Pre-start Manus launch-process ownership data flow"
require_documented 'waits only for the bounded launch grace' docs/DATA_FLOW_INVENTORY.md "Bounded Manus registration unwind data flow"
require_documented 'retaining its launch task, marker and credential' docs/DATA_FLOW_INVENTORY.md "Unresolved Manus registration cleanup ownership"
require_documented '409, 429/rate-limit' docs/DATA_FLOW_INVENTORY.md "Conflict and rate-limit registration ambiguity data flow"
require_documented 'GET /v2/webhook\.list' docs/DATA_FLOW_INVENTORY.md "Manus account-inventory destination"
require_documented 'active.*exact URL digest.*startedAt ± 300s' docs/DATA_FLOW_INVENTORY.md "Manus recovery attribution data flow"
require_documented 'multiple local attempts with the same digest.*delete nothing' docs/DATA_FLOW_INVENTORY.md "Ambiguous Manus recovery retention data flow"
require_documented 'Bound discovered IDs retry directly across restart' docs/DATA_FLOW_INVENTORY.md "Bound Manus ID retry data flow"
require_documented 'Real-account create → signed delivery → list/delete.*read-after-create/read-after-delete' docs/DATA_FLOW_INVENTORY.md "Remaining Manus live-consistency gate"
require_documented 'HTTP 2xx plus JSON `ok == true`' docs/DATA_FLOW_INVENTORY.md "Confirmed Manus deletion data flow"
require_documented 'failure/`ok:false` retains the ID' docs/DATA_FLOW_INVENTORY.md "Failed Manus deletion retention data flow"
require_documented 'The v6\.85 Manus transaction matrix' docs/CI_DIAGNOSTICS.md "Hermetic Manus v6.85 diagnostics matrix"
require_documented 'keys below 2,048 bits fail closed' docs/CI_DIAGNOSTICS.md "Weak Manus RSA diagnostic"
require_documented 'old-generation authentication' docs/CI_DIAGNOSTICS.md "Stale Manus generation diagnostic"
require_documented 'every accepted webhook ID is persisted' docs/CI_DIAGNOSTICS.md "Multi-ID Manus persistence diagnostic"
require_documented 'HTTP 2xx with `ok:false`' docs/CI_DIAGNOSTICS.md "Unconfirmed Manus deletion diagnostic"
require_documented 'retains the ID, the API credential' docs/CI_DIAGNOSTICS.md "Manus credential-retention diagnostic"
require_documented 'Connect to join an in-flight removal' docs/CI_DIAGNOSTICS.md "Manus replacement-key diagnostic"
require_documented 'cleanup-only manager also recovers multiple persisted IDs' docs/CI_DIAGNOSTICS.md "Polling-only Manus cleanup diagnostic"
require_documented 'ManusRealtimeTrust\.liveV2AcceptanceComplete' docs/CI_DIAGNOSTICS.md "Manus realtime release-gate diagnostic"
require_documented 'remains false, no real-account accepted artifact exists' docs/CI_DIAGNOSTICS.md "Manus realtime release limitation"
require_documented 'persisted sibling IDs' docs/INTERFACE_CONTRACT.md "Manus sibling-ID cleanup ordering contract"
require_documented 'joined ID 失败不能把其他 ID' docs/INTERFACE_CONTRACT.md "Manus sibling-ID failure isolation contract"
require_documented 'reconciliation 后执行 terminal gate' docs/INTERFACE_CONTRACT.md "Manus stop terminal recovery gate"
require_documented '任一状态仍存在都必须 fail closed' docs/INTERFACE_CONTRACT.md "Manus nonterminal recovery-state failure contract"
require_documented 'Keychain save 失败' docs/INTERFACE_CONTRACT.md "Manus replacement-save failure contract"
require_documented 'read back 持久源' docs/INTERFACE_CONTRACT.md "Manus replacement-save read-back contract"
require_documented '正常 Quit 的服务清理屏障' docs/INTERFACE_CONTRACT.md "Normal-Quit service barrier contract"
require_documented 'TaskStoreShutdownResult\.completed.*cleanupPending' docs/INTERFACE_CONTRACT.md "Low-cardinality TaskStore shutdown result"
require_documented 'in-flight Disconnect removal.*sleep suspension.*poller.*tunnel.*local listener' docs/INTERFACE_CONTRACT.md "TaskStore shutdown join ownership"
require_documented 'cleanup body.*Disconnect' docs/INTERFACE_CONTRACT.md "Queued Disconnect shutdown contract"
require_documented 'listener retry/restart task' docs/INTERFACE_CONTRACT.md "Queued listener-retry shutdown contract"
require_documented 'current operation \+ retiring operations' docs/INTERFACE_CONTRACT.md "Superseded poll ownership contract"
require_documented 'current/retiring serve.*readiness operations' docs/INTERFACE_CONTRACT.md "Superseded local-listener ownership contract"
require_documented '当前与全部已退役 operations' docs/INTERFACE_CONTRACT.md "Strict join of superseded operations"
require_documented 'cleanup 失败时返回 `\.cleanupPending`' docs/INTERFACE_CONTRACT.md "Quit cleanup-pending contract"
require_documented '`webhookRecoveryStateV1` envelope' docs/INTERFACE_CONTRACT.md "Quit cleanup-capability retention"
require_documented 'two-second hard timeout|two-second.*timeout' docs/DATA_FLOW_INVENTORY.md "Bounded AppKit Quit timeout data flow"
require_documented 'Yielded duplicate, Performance QA and hermetic Production smoke return `\.terminateNow`' docs/DATA_FLOW_INVENTORY.md "Side-effect-free termination bypass data flow"
require_documented 'joins bootstrap, an entry-time Disconnect' docs/DATA_FLOW_INVENTORY.md "Normal-Quit joined Disconnect data flow"
require_documented 'queued local start/retry ownership' docs/DATA_FLOW_INVENTORY.md "Normal-Quit joined local-retry data flow"
require_documented 'current and superseded poll/serve/readiness/event-delivery operation' docs/DATA_FLOW_INVENTORY.md "Superseded service-task and delivery-drain join data flow"
require_documented 'resolves queued action barriers as `false`' docs/DATA_FLOW_INVENTORY.md "Neutral queued-action shutdown data flow"
require_documented 'callback-owned stop uses its exact TaskLocal drain/server token' docs/DATA_FLOW_INVENTORY.md "Local Hook self-stop exclusion data flow"
require_documented 'later external stop strictly joins them' docs/DATA_FLOW_INVENTORY.md "Local Hook external strict-join data flow"
require_documented 'credential and authoritative `webhookRecoveryStateV1` envelope' docs/DATA_FLOW_INVENTORY.md "Quit failure cleanup-capability persistence data flow"
require_documented 'v6\.85 normal-Quit matrix' docs/CI_DIAGNOSTICS.md "Normal-Quit CI diagnostic matrix"
require_documented 'retained operation joins an existing Disconnect, sleep suspension, poller' docs/CI_DIAGNOSTICS.md "TaskStore shutdown ownership diagnostic"
require_documented 'authoritative ledger is nonempty' docs/CI_DIAGNOSTICS.md "Tunnel stop nonempty-ledger diagnostic"
require_documented 'registered Disconnect whose cleanup body has not started' docs/CI_DIAGNOSTICS.md "Queued Disconnect diagnostic"
require_documented 'retry is joined before the concrete listener stops' docs/CI_DIAGNOSTICS.md "Queued local-listener retry diagnostic"
require_documented 'exact same low-cardinality' docs/CI_DIAGNOSTICS.md "TaskStore shutdown result diagnostic"
require_documented '`completed` / `cleanupPending` result' docs/CI_DIAGNOSTICS.md "TaskStore shutdown result values"
require_documented 'Joinable-stop regressions' docs/CI_DIAGNOSTICS.md "Joinable service-stop diagnostics"
require_documented 'current and retiring poll' docs/CI_DIAGNOSTICS.md "Retiring poll ownership diagnostic"
require_documented 'every retired' docs/CI_DIAGNOSTICS.md "Retiring listener ownership diagnostic"
require_documented 'same port can be rebound immediately' docs/CI_DIAGNOSTICS.md "Immediate listener-port reuse diagnostic"
require_documented 'normal owner chooses `terminateLater`' docs/CI_DIAGNOSTICS.md "AppKit owner termination diagnostic"
require_documented 'two-second hard timeout race one private token' docs/CI_DIAGNOSTICS.md "Tokenized Quit timeout diagnostic"
require_documented 'Yielded' docs/CI_DIAGNOSTICS.md "AppKit termination bypass modes diagnostic"
require_documented 'duplicates, Performance QA and hermetic launch smoke choose `terminateNow`' docs/CI_DIAGNOSTICS.md "AppKit termination bypass decision diagnostic"
require_documented 'credential-releasing stop.*entry-time deletion operations' docs/manus-api-field-notes.md "Manus stop-entry ownership field note"
require_documented 'Keychain save.*read back' docs/manus-api-field-notes.md "Manus replacement-save recovery field note"
require_documented 'memoized.*TaskStore\.shutdown\(\)' docs/manus-api-field-notes.md "Awaited normal-Quit field note"
require_documented 'liveV2AcceptanceComplete.*`false`' docs/manus-api-field-notes.md "Manus realtime gate remains disabled in field notes"
require_documented 'webhook\.list.*账号鉴权' docs/manus-api-field-notes.md "Manus account-level list field note"
require_documented 'set → synchronize → decode/readback → mirrors' docs/manus-api-field-notes.md "Manus recovery persistence order field note"
require_documented 'startedAt ± 300s' docs/manus-api-field-notes.md "Manus exact recovery window field note"
require_documented '多个本机 marker 同 digest 时删除零项' docs/manus-api-field-notes.md "Manus ambiguous-attribution field note"
require_documented 'discoveredWebhookIDs.*跨重启保留' docs/manus-api-field-notes.md "Manus discovered-ID retry field note"
require_documented '404 `not_found`' docs/manus-api-field-notes.md "Manus not-found retry completion field note"
require_documented 'read-after-create/read-after-delete' docs/manus-api-field-notes.md "Manus live consistency limitation field note"
require_documented 'GET /v2/webhook\.list' PRIVACY.md "English Manus account-inventory disclosure"
require_documented 'GET /v2/webhook\.list' PRIVACY.md "Chinese Manus account-inventory disclosure"
require_documented 'read-after-create/read-after-delete' PRIVACY.md "Manus live-consistency privacy limitation"

if rg -n 'no provider-side recovery/reconciliation capability|没有 provider-side lookup/recovery|没有 provider-side lookup/recovery/reconciliation' \
    PRIVACY.md docs/DATA_FLOW_INVENTORY.md docs/INTERFACE_CONTRACT.md docs/manus-api-field-notes.md; then
  fail "Canonical Manus documents must not claim the official webhook.list recovery API is unavailable"
fi
require_documented '正常 Quit 不再 fire-and-forget' docs/Codex-Plan.md "Normal-Quit implementation plan"
require_documented 'AppKit 普通 owner.*`\.terminateLater`' docs/Codex-Plan.md "AppKit termination plan"
require_documented 'Plan Review Markdown 单次后台渲染' docs/INTERFACE_CONTRACT.md "Plan Review off-main rendering contract"
require_documented '262,144 UTF-8' docs/INTERFACE_CONTRACT.md "Plan Review Markdown byte contract"
require_documented '512 个块' docs/INTERFACE_CONTRACT.md "Plan Review SwiftUI block bound"
require_documented 'once per request in an on-device detached worker' docs/DATA_FLOW_INVENTORY.md "Plan Review detached rendering data flow"
require_documented 'at most 512 complete blocks' docs/DATA_FLOW_INVENTORY.md "Plan Review block-bound data flow"
require_documented '262,144 UTF-8' PRIVACY.md "English Plan Review byte disclosure"
require_documented 'at most 512 complete blocks' PRIVACY.md "English Plan Review block disclosure"
require_documented '最多 512 个完整块' PRIVACY.md "Chinese Plan Review block disclosure"
require_documented 'Plan Review render isolation' docs/PERFORMANCE_QA.md "Plan Review rendering performance QA"
require_documented 'Thread\.isMainThread == false' docs/PERFORMANCE_QA.md "Plan Review real-thread assertion"
require_documented '展开面板叶子时钟隔离' docs/INTERFACE_CONTRACT.md "Panel leaf-clock isolation contract"
require_documented 'Panel clock leaf isolation' docs/PERFORMANCE_QA.md "Panel leaf-clock performance QA"
require_documented 'Settings Agent Hook 配置 I/O 主线程隔离' docs/INTERFACE_CONTRACT.md "Settings Agent configuration I/O contract"
require_documented 'Welcome 连接配置操作所有权' docs/INTERFACE_CONTRACT.md "Welcome Agent configuration operation contract"
require_documented 'LocalAgentConfigurationExecutor.*detached worker' docs/INTERFACE_CONTRACT.md "Settings detached configuration executor"
require_documented 'Local Agent configuration presentation I/O' docs/DATA_FLOW_INVENTORY.md "Settings Agent configuration presentation data flow"
require_documented 'MainActor-to-non-main execution' docs/DATA_FLOW_INVENTORY.md "Settings non-main execution evidence"
require_documented 'on-device background worker' PRIVACY.md "English Settings configuration worker disclosure"
require_documented 'do not block the interface' PRIVACY.md "English Settings main-thread disclosure"
require_documented '本机后台 worker' PRIVACY.md "Chinese Settings configuration worker disclosure"
require_documented '不会阻塞界面' PRIVACY.md "Chinese Settings main-thread disclosure"
require_documented 'Settings Agent configuration responsiveness' docs/PERFORMANCE_QA.md "Settings configuration responsiveness QA"
require_documented 'Settings Agent 配置全局操作所有权' docs/INTERFACE_CONTRACT.md "Settings cross-pane Agent mutation contract"
require_documented 'Settings Agent mutation ownership across panes' docs/PERFORMANCE_QA.md "Settings cross-pane mutation QA"
require_documented 'one owner across every pane' docs/DATA_FLOW_INVENTORY.md "Settings cross-pane mutation data flow"
require_documented 'one in-memory mutation owner' PRIVACY.md "English Settings cross-pane mutation disclosure"
require_documented '页面切换层之上保留一个仅内存的 mutation owner' PRIVACY.md "Chinese Settings cross-pane mutation disclosure"
require_documented 'Welcome connection operation ownership' docs/PERFORMANCE_QA.md "Welcome configuration responsiveness QA"
require_documented 'Support 诊断导出 I/O 主线程隔离' docs/INTERFACE_CONTRACT.md "Support diagnostics I/O isolation contract"
require_documented 'SupportDiagnosticsIOExecutor.*detached worker' docs/INTERFACE_CONTRACT.md "Support diagnostics detached executor"
require_documented 'MainActor-to-non-main diagnostic execution' docs/DATA_FLOW_INVENTORY.md "Support diagnostics non-main data flow"
require_documented 'transaction run in an on-device background worker' PRIVACY.md "English diagnostic background-worker disclosure"
require_documented '诊断准备.*本机后台 worker' PRIVACY.md "Chinese diagnostic background-worker disclosure"
require_documented 'Support diagnostics responsiveness' docs/PERFORMANCE_QA.md "Support diagnostics responsiveness QA"
require_documented 'Settings and Welcome perform' PRIVACY.md "English Welcome configuration worker disclosure"
require_documented 'Settings 与 Welcome' PRIVACY.md "Chinese Welcome configuration worker disclosure"
require_documented 'Thread\.isMainThread == false' docs/PERFORMANCE_QA.md "Settings configuration real-thread assertion"
require_documented '商业政策审批记录输入边界' docs/INTERFACE_CONTRACT.md "Commercial policy input boundary"
require_documented 'last-key-wins' docs/INTERFACE_CONTRACT.md "Commercial policy duplicate-key ambiguity boundary"
require_documented 'decisionState: required' docs/INTERFACE_CONTRACT.md "Commercial policy remains unapproved"
require_documented 'Welcome 编辑栏几何' docs/INTERFACE_CONTRACT.md "Welcome editorial geometry contract"
require_documented '32pt.*264pt.*28pt.*404pt' docs/INTERFACE_CONTRACT.md "Welcome fixed-width composition"
require_documented '权威测试 SwiftPM 构建图隔离' docs/INTERFACE_CONTRACT.md "Authoritative SwiftPM test-graph isolation contract"
require_documented '\.build/tests-authoritative' docs/INTERFACE_CONTRACT.md "Dedicated authoritative test scratch"
require_documented '准确 66 次调用' docs/INTERFACE_CONTRACT.md "Deterministic authoritative test invocation count"
require_documented 'swift test.*绕过' docs/INTERFACE_CONTRACT.md "Workflow direct-test bypass boundary"
require_documented '权威测试单写者锁' docs/INTERFACE_CONTRACT.md "Authoritative test single-writer contract"
require_documented 'tests-authoritative\.lock' docs/INTERFACE_CONTRACT.md "Authoritative test lock path"
require_documented '/usr/bin/lockf -s -t 0 9' docs/INTERFACE_CONTRACT.md "Non-waiting BSD descriptor lock"
require_documented '第二个权威入口.*swift.*命令前退出' docs/INTERFACE_CONTRACT.md "Contended test graph fails before Swift"
require_documented 'Maintainer authoritative test ownership' docs/DATA_FLOW_INVENTORY.md "Authoritative test lock data-flow boundary"
require_documented 'No content: one fixed zero-byte lock file' docs/DATA_FLOW_INVENTORY.md "Authoritative lock contains no data"
require_documented 'GitHub 仓库审计失败分类与诊断隐私' docs/INTERFACE_CONTRACT.md "GitHub audit failure-classification contract"
require_documented 'GitHub API network unavailable' docs/INTERFACE_CONTRACT.md "Low-cardinality GitHub network failure"
require_documented '1 byte–64 KiB' docs/INTERFACE_CONTRACT.md "Bounded GitHub API diagnostic classification"
require_documented '原始错误不得回显' docs/INTERFACE_CONTRACT.md "GitHub API raw-diagnostic exclusion"
require_documented 'connection reset.*HTTP 401.*HTTP 403.*HTTP 404' docs/INTERFACE_CONTRACT.md "GitHub API classification fixtures"
require_documented 'Dock 重试与进程夹具调度隔离' docs/INTERFACE_CONTRACT.md "Deterministic Dock and process-fixture scheduling contract"
require_documented 'production 默认 timeout 继续固定为 3 秒' docs/INTERFACE_CONTRACT.md "Production Codex timeout isolation"
require_documented 'FixtureError\.pidNotPublished' docs/INTERFACE_CONTRACT.md "Explicit process-fixture PID failure"
require_documented 'macOS 状态菜单实时摘要与隐私边界' docs/INTERFACE_CONTRACT.md "Live status-menu contract"
require_documented 'withObservationTracking' docs/INTERFACE_CONTRACT.md "Event-driven status-menu refresh contract"
require_documented '任务标题、Session ID、路径' docs/INTERFACE_CONTRACT.md "Status-menu privacy boundary"
require_documented '三种 App 构建风味的可执行产物边界' docs/INTERFACE_CONTRACT.md "Artifact-level build-flavor contract"
require_documented '21 个' docs/INTERFACE_CONTRACT.md "Per-marker build-flavor negative matrix"
require_documented 'Maintainer build-flavor executable inspection' docs/DATA_FLOW_INVENTORY.md "Build-flavor executable data flow"
require_documented 'No raw executable strings' docs/DATA_FLOW_INVENTORY.md "Build-flavor raw-string exclusion"
require_documented 'fixed build-flavor markers' PRIVACY.md "English build-flavor inspection disclosure"
require_documented '六个固定构建风味标记' PRIVACY.md "Chinese build-flavor inspection disclosure"
require_documented '离线法律文件与签名 App 字节绑定' docs/INTERFACE_CONTRACT.md "Offline bundled legal-document contract"
require_documented '10 个负向用例' docs/INTERFACE_CONTRACT.md "Legal-document attack-fixture contract"
require_documented 'App 内法律资源 descriptor 原子读取边界' docs/INTERFACE_CONTRACT.md "Runtime legal-document descriptor contract"
require_documented 'O_RDONLY.*O_NOFOLLOW.*O_CLOEXEC.*O_NONBLOCK' docs/INTERFACE_CONTRACT.md "Runtime legal-document open flags"
require_documented 'dev/inode/mode/nlink/size/mtime/ctime' docs/INTERFACE_CONTRACT.md "Runtime legal-document identity revalidation"
require_documented 'Bundled Privacy / Terms reading' docs/DATA_FLOW_INVENTORY.md "Bundled legal-document data flow"
require_documented 'descriptor-backed, no-follow.*1–512 KiB' docs/DATA_FLOW_INVENTORY.md "Runtime legal-document bounded data flow"
require_documented 'PR CI hermetic App 真实启动与正常退出' docs/INTERFACE_CONTRACT.md "Hermetic PR launch-smoke contract"
require_documented 'NSRunningApplication.*terminate' docs/INTERFACE_CONTRACT.md "Exact-PID normal App termination contract"
require_documented '8 个一秒存活样本' docs/INTERFACE_CONTRACT.md "Eight-sample launch survival contract"
require_documented 'Maintainer hermetic App launch and performance sampling' docs/DATA_FLOW_INVENTORY.md "Hermetic maintainer launch-smoke data flow"
require_documented 'eight bounded CPU/RSS samples' PRIVACY.md "English hermetic launch-smoke disclosure"
require_documented '八个有界 CPU/RSS 样本' PRIVACY.md "Chinese hermetic launch-smoke disclosure"
require_documented 'Performance 证据文件 descriptor 所有权' docs/INTERFACE_CONTRACT.md "Atomic performance-evidence file ownership contract"
require_documented 'noclobber.*descriptor 7/8/9' docs/INTERFACE_CONTRACT.md "Exclusive performance-evidence descriptor set"
require_documented 'RDONLY.*NOFOLLOW.*NONBLOCK' docs/INTERFACE_CONTRACT.md "No-follow performance CSV snapshot"
require_documented 'Performance readiness App-log 原子读取' docs/INTERFACE_CONTRACT.md "Atomic readiness App-log read contract"
require_documented 'Performance 输入 App 私有快照与执行身份' docs/INTERFACE_CONTRACT.md "Frozen Performance App execution contract"
require_documented '真正进入.*6-Mach-O.*launch' docs/INTERFACE_CONTRACT.md "Private-only Performance App launch contract"
require_documented 'selected_executable_sha256' docs/INTERFACE_CONTRACT.md "Selected Performance App summary hash"
require_documented 'isolated_app_snapshot=true' docs/INTERFACE_CONTRACT.md "Performance App isolation summary binding"
require_documented 'FIFO.*malformed or duplicate.*reverse/out-of-window' docs/DATA_FLOW_INVENTORY.md "Readiness snapshot failure classes"
require_documented 'random private `0700` sampler root' docs/DATA_FLOW_INVENTORY.md "Private Performance App snapshot data flow"
require_documented 'selected-source replacement' docs/DATA_FLOW_INVENTORY.md "Selected Performance App replacement failure"
require_documented 'current-user `0600` single-link descriptors' PRIVACY.md "English performance-evidence file boundary disclosure"
require_documented '当前用户 `0600` 单硬链接 descriptor' PRIVACY.md "Chinese performance-evidence file boundary disclosure"
require_documented 'App-log writer identity.*malformed or duplicate' PRIVACY.md "English bounded readiness snapshot disclosure"
require_documented 'writer 身份绑定的同类私有快照' PRIVACY.md "Chinese bounded readiness snapshot disclosure"
require_documented 'malformed/重复 marker' PRIVACY.md "Chinese strict readiness parser disclosure"
require_documented "sampler's random private" PRIVACY.md "English private Performance App snapshot disclosure"
require_documented '`0700` directory' PRIVACY.md "English private Performance App directory disclosure"
require_documented '来源被替换时不发布 summary' PRIVACY.md "Chinese Performance App replacement disclosure"
require_documented 'PR CI Performance summary 进程内交付' docs/INTERFACE_CONTRACT.md "In-memory PR performance summary contract"
require_documented 'workflow 禁止再对' docs/INTERFACE_CONTRACT.md "Post-exit public summary reopen prohibition"
require_documented 'dev-island-launch-smoke\.summary\.txt' docs/INTERFACE_CONTRACT.md "Public performance summary path contract"
require_documented '本地 listener 无副作用 transport 夹具' docs/INTERFACE_CONTRACT.md "Hermetic local-listener transport contract"
require_documented '零 stderr' docs/INTERFACE_CONTRACT.md "Hermetic local-listener silent diagnostic contract"
require_documented 'App SwiftPM 外置 scratch 边界' docs/INTERFACE_CONTRACT.md "External App SwiftPM scratch contract"
require_documented 'prepare-scratch' docs/INTERFACE_CONTRACT.md "Validated external SwiftPM scratch boundary"
require_documented 'Maintainer external SwiftPM App scratch' docs/DATA_FLOW_INVENTORY.md "External SwiftPM scratch data flow"
require_documented 'no Agent configuration' docs/DATA_FLOW_INVENTORY.md "External SwiftPM scratch product-data exclusion"
require_documented 'bounded sampler-stdout shell variable' docs/DATA_FLOW_INVENTORY.md "In-process performance acceptance data flow"
require_documented 'Production App hermetic 真实启动门禁' docs/INTERFACE_CONTRACT.md "Production App launch-smoke contract"
require_documented '精确参数\+环境双重 opt-in' docs/INTERFACE_CONTRACT.md "Production launch-smoke dual opt-in boundary"
require_documented 'readiness 后及每个样本.*没有网络 socket' docs/INTERFACE_CONTRACT.md "Production launch-smoke repeated network isolation"
require_documented 'Maintainer Production App hermetic launch smoke' docs/DATA_FLOW_INVENTORY.md "Production launch-smoke data flow"
require_documented 'every one-second sample verify no network socket' docs/DATA_FLOW_INVENTORY.md "Production launch-smoke repeated isolation data flow"
require_documented 'maintainer-only `production-launch-smoke`' PRIVACY.md "English Production launch-smoke disclosure"
require_documented '每一秒只检查精确 PID 是否出现网络 socket' PRIVACY.md "Chinese Production launch-smoke disclosure"
require_documented 'real Production Bundle has a maintainer-only hermetic launch mode' docs/LEGAL_RELEASE_CHECKLIST.md "Production launch-smoke release gate"
require_documented 'does not reopen the runner-temporary' PRIVACY.md "English in-memory performance summary disclosure"
require_documented 'producer 退出后不再重开 runner 临时' PRIVACY.md "Chinese in-memory performance summary disclosure"
require_documented 'exact, read-only copies of this notice' PRIVACY.md "English bundled legal-document disclosure"
require_documented '精确只读副本' PRIVACY.md "Chinese bundled legal-document disclosure"
require_documented 'Current Support actions are preceded by offline Privacy / Terms entries' docs/LEGAL_RELEASE_CHECKLIST.md "Current in-app legal entry gate"
require_documented 'Manus 真实账号验收证据边界' docs/INTERFACE_CONTRACT.md "Manus live-evidence contract"
require_documented 'O_NOFOLLOW.*1 byte–64 KiB' docs/INTERFACE_CONTRACT.md "Bounded no-follow Manus transcript validation"
require_documented '只有 CLI exit 0.*--require-accepted' docs/INTERFACE_CONTRACT.md "Fail-closed Manus accepted marker"
require_documented 'Manus 验收编译输入闭包' docs/INTERFACE_CONTRACT.md "Manus complete build-input closure"
require_documented 'ignored local file' docs/INTERFACE_CONTRACT.md "Dependency checkout contamination boundary"
require_documented 'TOOLCHAIN_BEFORE/AFTER_BUILD' docs/INTERFACE_CONTRACT.md "Manus toolchain stability evidence"
require_documented 'GitHub Workflow 内嵌 Shell 语法边界' docs/INTERFACE_CONTRACT.md "Workflow run-shell syntax contract"
require_documented '`/bin/bash -n`' docs/INTERFACE_CONTRACT.md "Non-executing workflow Bash parser"
require_documented '同时验证 `ci\.yml` 与 `release\.yml`' docs/INTERFACE_CONTRACT.md "Both workflows checked before tagged execution"
require_documented 'GitHub Workflow YAML 结构歧义边界' docs/INTERFACE_CONTRACT.md "Workflow YAML ambiguity contract"
require_documented 'exactly one YAML document' docs/INTERFACE_CONTRACT.md "Single-document workflow boundary"
require_documented '`on` 与 `true`' docs/INTERFACE_CONTRACT.md "Resolved duplicate workflow-key boundary"
require_documented '20,000 个 AST node' docs/INTERFACE_CONTRACT.md "Bounded workflow YAML structure"
require_documented 'GitHub Workflow 有效 Shell 解析边界' docs/INTERFACE_CONTRACT.md "Workflow effective-shell contract"
require_documented 'step > job defaults > workflow defaults' docs/INTERFACE_CONTRACT.md "Workflow shell precedence contract"
require_documented '精确 `bash` 或 `/bin/bash`' docs/INTERFACE_CONTRACT.md "Exact reviewed workflow shells"
require_documented '仓库脚本无执行语法闭包' docs/INTERFACE_CONTRACT.md "Repository script syntax-closure contract"
require_documented "${repository_bash_count} 个 Bash 与 ${repository_ruby_count} 个 Ruby" docs/INTERFACE_CONTRACT.md "Complete current repository script closure"
require_documented '前半段写 marker 的命令仍会先执行' docs/INTERFACE_CONTRACT.md "Bash partial-execution threat"
require_documented 'Swift 脚本 stdin-only Parse 闭包' docs/INTERFACE_CONTRACT.md "Swift script parse-closure contract"
require_documented "${repository_bash_count} Bash \\+ ${repository_ruby_count} Ruby \\+ ${repository_swift_count} Swift" docs/INTERFACE_CONTRACT.md "Complete current three-language script closure"
require_documented '`/usr/bin/swiftc -parse -`' docs/INTERFACE_CONTRACT.md "Non-executing Swift parser"
require_documented 'App 构建输出与原子发布边界' docs/INTERFACE_CONTRACT.md "Atomic App build-output contract"
require_documented 'app-build-output-boundary\.rb prepare' docs/INTERFACE_CONTRACT.md "Caller-controlled build-directory boundary"
require_documented '本地 Agent Loopback 浏览器请求边界' docs/INTERFACE_CONTRACT.md "Local Hook browser-request contract"
require_documented 'Access-Control-Allow-Origin' docs/INTERFACE_CONTRACT.md "Local Hook CORS denial contract"
require_documented '本地 CLI 版本探针调度稳定性' docs/INTERFACE_CONTRACT.md "Local CLI probe stability contract"
require_documented '20 轮，共启动' docs/INTERFACE_CONTRACT.md "Local CLI probe CI stress count"
require_documented '本地准备度重试语义与视觉层级' docs/INTERFACE_CONTRACT.md "Readiness retry presentation contract"
require_documented '禁止计入' docs/INTERFACE_CONTRACT.md "Transient checks excluded from setup-action count"
require_documented 'tmux 后台子进程清理调度稳定性' docs/INTERFACE_CONTRACT.md "tmux cleanup stability contract"
require_documented 'descendant 清理 20 轮' docs/INTERFACE_CONTRACT.md "tmux cleanup PR stress count"
require_documented '解锁性能证据与显示会话判定' docs/INTERFACE_CONTRACT.md "Unlocked performance evidence contract"
require_documented 'kCGSSessionOnConsoleKey=true' docs/INTERFACE_CONTRACT.md "Active-console display-session proof"
require_documented 'screen_state_initial=unlocked' docs/INTERFACE_CONTRACT.md "Performance summary initial screen state"
require_documented 'Settings 控件节奏与视觉证据' docs/INTERFACE_CONTRACT.md "Settings control-rhythm contract"
require_documented 'switch 固定在卡片右边线' docs/INTERFACE_CONTRACT.md "Localized Settings switch alignment"
require_documented 'Production 更新页版本号只允许来自 App Bundle' docs/INTERFACE_CONTRACT.md "Production update-version source"
require_documented '自动更新发布私钥进程边界' docs/INTERFACE_CONTRACT.md "Sparkle release-key process boundary"
require_documented '`env -i`' docs/INTERFACE_CONTRACT.md "Sparkle generator minimal environment"
require_documented 'PR CI 脱敏诊断文件边界' docs/INTERFACE_CONTRACT.md "PR CI diagnostic file-boundary contract"
require_documented 'schema v2 以低基数 `sourceStatus`' docs/INTERFACE_CONTRACT.md "Bounded CI diagnostic source status"
require_documented '本地 Agent 双向 Hook 交付顺序' docs/INTERFACE_CONTRACT.md "Synchronous local-action ordering contract"
require_documented '先 `await` lifecycle 交付' docs/INTERFACE_CONTRACT.md "Lifecycle-before-action delivery order"
require_documented 'Maintainer PR CI diagnostics' docs/DATA_FLOW_INVENTORY.md "Maintainer CI diagnostic data flow"
require_documented 'does not collect data from a' PRIVACY.md "CI diagnostics exclude installed-App collection"
require_documented '两个脱敏文件组成的 artifact' PRIVACY.md "Chinese CI diagnostic retention notice"
require_documented 'Maintainer workflow shell validation' docs/DATA_FLOW_INVENTORY.md "Maintainer workflow syntax data flow"
require_documented 'No Secret value or installed-App data is read' docs/DATA_FLOW_INVENTORY.md "Workflow syntax validator data exclusion"
require_documented 'duplicate/resolved-colliding mapping keys' docs/DATA_FLOW_INVENTORY.md "Workflow YAML ambiguity data boundary"
require_documented 'workflow/job `defaults.run.shell`' docs/DATA_FLOW_INVENTORY.md "Workflow inherited-shell data boundary"
require_documented 'Maintainer repository script syntax validation' docs/DATA_FLOW_INVENTORY.md "Repository script syntax data flow"
require_documented 'No repository script is executed' docs/DATA_FLOW_INVENTORY.md "Repository script no-execution boundary"
require_documented "${repository_bash_count} Bash \\+ ${repository_ruby_count} Ruby \\+ ${repository_swift_count} Swift" docs/DATA_FLOW_INVENTORY.md "Three-language repository script inventory"
require_documented "collects all ${repository_bash_count} Bash, ${repository_ruby_count} Ruby, and ${repository_swift_count} Swift" docs/GITHUB_REPOSITORY_CONTROLS.md "GitHub controls repository script inventory"
require_documented '固定 create-dmg 发布工具边界' docs/INTERFACE_CONTRACT.md "Pinned create-dmg release-tool contract"
require_documented 'size/hash 通过前不得调用 gzip/tar' docs/INTERFACE_CONTRACT.md "Digest-before-parser release-tool boundary"
require_documented '归档形状固定为 28 个 tar record' docs/INTERFACE_CONTRACT.md "Pinned create-dmg archive record count"
require_documented '恰好 27 个 filesystem entry' docs/INTERFACE_CONTRACT.md "Pinned create-dmg filesystem entry count"
require_documented '精确 369 bytes' docs/INTERFACE_CONTRACT.md "Pinned create-dmg runtime manifest size"
require_documented '35565e6e5d1086014d94fdddd246b8daa4b33bf3d6b9b49a1a9dac2d3a57526f' docs/INTERFACE_CONTRACT.md "Pinned create-dmg runtime manifest digest"
require_documented '`run-pinned-create-dmg\.rb`' docs/INTERFACE_CONTRACT.md "Descriptor-bound create-dmg execution contract"
require_documented '22,095 bytes' docs/INTERFACE_CONTRACT.md "Pinned transformed create-dmg script"
require_documented '46644c8da0d7eb1258e3ef05dd72967ca270d698df28d2aa6abd9402205e5beb' docs/INTERFACE_CONTRACT.md "Pinned transformed create-dmg digest"
require_documented '重新打开.*CREATE_DMG_EXECUTABLE' docs/INTERFACE_CONTRACT.md "No pathname reopen after create-dmg verification"
require_documented '不得据此宣称产品已经完整商业可发布' docs/INTERFACE_CONTRACT.md "Pinned-tool commercial-release limitation"
require_documented 'Maintainer pinned release-tool preparation' docs/DATA_FLOW_INVENTORY.md "Pinned release-tool data flow"
require_documented 'No installed-App data, product user data.*other Secret is read or sent' docs/DATA_FLOW_INVENTORY.md "Pinned release-tool credential exclusion"
require_documented 'One logical download, with at most four HTTPS GET attempts' docs/DATA_FLOW_INVENTORY.md "Pinned release-tool retry disclosure"
require_documented 'pre-secret preparer performs one clean-environment `--pure-version` probe' docs/DATA_FLOW_INVENTORY.md "Pinned release-tool version-probe disclosure"
require_documented '/bin/bash /dev/fd/N' docs/DATA_FLOW_INVENTORY.md "Anonymous descriptor create-dmg execution"
require_documented 'Maintainer Release signing-capability isolation' docs/DATA_FLOW_INVENTORY.md "Release signing-capability data flow"
require_documented 'exactly 28 tar records' docs/GITHUB_REPOSITORY_CONTROLS.md "GitHub controls create-dmg record count"
require_documented '369-byte `runtime\.SHA256`' docs/GITHUB_REPOSITORY_CONTROLS.md "GitHub controls create-dmg manifest size"
require_documented '35565e6e5d1086014d94fdddd246b8daa4b33bf3d6b9b49a1a9dac2d3a57526f' docs/GITHUB_REPOSITORY_CONTROLS.md "GitHub controls create-dmg manifest digest"
require_documented '46644c8da0d7eb1258e3ef05dd72967ca270d698df28d2aa6abd9402205e5beb' docs/GITHUB_REPOSITORY_CONTROLS.md "GitHub controls transformed create-dmg digest"
require_documented '`Tear down App signing keychain`' docs/GITHUB_REPOSITORY_CONTROLS.md "GitHub controls App signing teardown"
require_documented '`Tear down DMG signing keychain`' docs/GITHUB_REPOSITORY_CONTROLS.md "GitHub controls DMG signing teardown"
require_documented 'not the primary capability boundary' docs/GITHUB_REPOSITORY_CONTROLS.md "GitHub controls final cleanup limitation"
require_documented 'Maintainer Sparkle release cryptographic verification' docs/DATA_FLOW_INVENTORY.md "Sparkle release cryptographic data flow"
require_documented '自动更新 Ed25519 密码学闭环' docs/INTERFACE_CONTRACT.md "Sparkle Ed25519 release contract"
require_documented '完整 archive 与精确 feed prefix' docs/INTERFACE_CONTRACT.md "Sparkle signed-byte verification scope"
require_documented '自动更新 disposable old-to-new 真实闭环' docs/INTERFACE_CONTRACT.md "Sparkle disposable old-to-new update contract"
require_documented 'Maintainer disposable Sparkle old-to-new gate' docs/DATA_FLOW_INVENTORY.md "Sparkle disposable old-to-new data flow"
require_documented 'workflow YAML and Bash `run` steps' PRIVACY.md "English workflow syntax privacy notice"
require_documented 'ambiguous duplicate or multi-document YAML' PRIVACY.md "English workflow ambiguity privacy notice"
require_documented 'effective workflow/job/step shell' PRIVACY.md "English effective-shell privacy notice"
require_documented '静态解析仓库内的 workflow YAML' PRIVACY.md "Chinese workflow syntax privacy notice"
require_documented '重复键或多文档 YAML' PRIVACY.md "Chinese workflow ambiguity privacy notice"
require_documented 'workflow/job/step 的有效 shell' PRIVACY.md "Chinese effective-shell privacy notice"
require_documented 'all repository Bash, Ruby, and Swift scripts' PRIVACY.md "English repository script syntax privacy notice"
require_documented '全部仓库 Bash、Ruby 与 Swift 脚本' PRIVACY.md "Chinese repository script syntax privacy notice"
require_documented 'polling-only 模式提升为 `\.connected`' docs/INTERFACE_CONTRACT.md "Manus realtime downgrade contract"
require_documented 'Maintainer Manus live-acceptance evidence' docs/DATA_FLOW_INVENTORY.md "Maintainer Manus acceptance evidence flow"
require_documented 'maintainer-only live-acceptance' PRIVACY.md "English Manus evidence privacy notice"
require_documented '维护者主动运行的真实验收包装器' PRIVACY.md "Chinese Manus evidence privacy notice"
require_documented 'Maintainer Codex live-approval evidence' docs/DATA_FLOW_INVENTORY.md "Maintainer Codex approval evidence flow"
require_documented 'maintainer-only Codex live-approval' PRIVACY.md "English Codex evidence privacy notice"
require_documented '仅由维护者主动运行的 Codex 真实审批证据包装器' PRIVACY.md "Chinese Codex evidence privacy notice"
require_documented 'Codex 真实审批证据边界' docs/INTERFACE_CONTRACT.md "Codex approval evidence contract"
require_documented 'raw Codex JSONL/database are never copied' docs/DATA_FLOW_INVENTORY.md "Codex evidence raw-input exclusion"
require_documented 'worktree_state=dirty' docs/INTERFACE_CONTRACT.md "Codex evidence reproducibility limitation"
require_documented 'Maintainer Codex live-decision evidence' docs/DATA_FLOW_INVENTORY.md "Codex decision evidence flow"
require_documented 'explicit_island_deny.*neutral_timeout_fallback.*sandbox_rejection.*interrupted_attempt' docs/DATA_FLOW_INVENTORY.md "Codex decision outcome separation"
require_documented 'maintainer-only Codex live-decision' PRIVACY.md "English Codex decision privacy notice"
require_documented '仅供维护者使用的 Codex 拒绝/超时真实决策分类' PRIVACY.md "Chinese Codex decision privacy notice"
require_documented 'Codex 真实拒绝与超时分类证据边界' docs/INTERFACE_CONTRACT.md "Codex decision evidence contract"
require_documented '绝不 `eval`' docs/INTERFACE_CONTRACT.md "Codex recorded JavaScript no-evaluation boundary"
require_documented '后三类永远不能进入 accepted packager' docs/INTERFACE_CONTRACT.md "Codex negative classifications fail closed"
require_documented '旧结果不得' docs/INTERFACE_CONTRACT.md "Manus stale-poll suppression contract"
require_documented 'clearAPIKey\(\) async throws' docs/INTERFACE_CONTRACT.md "Manus disconnect integrity contract"
require_documented 'CommercialLicenseDocumentStoreError' docs/INTERFACE_CONTRACT.md "Commercial license storage error API"
require_documented 'CommercialLicenseDocumentStore' docs/INTERFACE_CONTRACT.md "Commercial license storage API"
require_documented 'importDocument\(' docs/INTERFACE_CONTRACT.md "Verified commercial license import API"
require_documented 'evaluateStored\(' docs/INTERFACE_CONTRACT.md "Stored commercial license evaluation API"
require_documented 'public func delete\(\) throws' docs/INTERFACE_CONTRACT.md "Commercial license deletion API"
require_documented 'commercial_license_v1' docs/INTERFACE_CONTRACT.md "Commercial license Keychain account contract"
require_documented 'WhenUnlockedThisDeviceOnly' docs/INTERFACE_CONTRACT.md "Commercial license device-only contract"
require_documented 'verify-before-save' docs/INTERFACE_CONTRACT.md "Commercial license fail-closed import contract"
require_documented 'CommercialActivationCode' docs/INTERFACE_CONTRACT.md "Commercial activation code API"
require_documented '`memset_s` 主动清零' docs/INTERFACE_CONTRACT.md "Commercial activation code erasure contract"
require_documented 'CommercialActivationTransport' docs/INTERFACE_CONTRACT.md "Commercial activation transport API"
require_documented 'CommercialLicenseActivationService' docs/INTERFACE_CONTRACT.md "Commercial activation service API"
require_documented 'cancelPendingActivation' docs/INTERFACE_CONTRACT.md "Commercial activation cancellation contract"
require_documented 'latest-operation-wins' docs/INTERFACE_CONTRACT.md "Commercial activation concurrency contract"
require_documented '决策面替代该会话的普通可点击 TaskCard' docs/INTERFACE_CONTRACT.md "Focused action-request presentation contract"
require_documented '总数使用 `session/sessions`' docs/INTERFACE_CONTRACT.md "Expanded-panel session language contract"
require_documented 'case connected, configured, updateRequired, disconnected' docs/INTERFACE_CONTRACT.md "Codex trust-aware Hook status contract"
require_documented 'snapshotResolvingVendorActivation' docs/INTERFACE_CONTRACT.md "Vendor activation resolution API"
require_documented '2 MiB 上限' docs/INTERFACE_CONTRACT.md "Codex trust-probe bound contract"

require_documented 'reviewInAgent\(command: "/hooks"\)' IslandCore/Sources/IslandCore/Connectors/Codex/CodexAgent.swift "Codex vendor-owned trust gate"
require_documented 'case configured' IslandCore/Sources/IslandCore/Connectors/Framework/LocalAgentHookDiagnostics.swift "Configured Hook diagnostic state"

rg -q 'PRIVACY\.md' README.md || fail "README must link the canonical privacy notice"
rg -q 'TERMS\.md' README.md || fail "README must link the canonical terms"
rg -q 'DATA_FLOW_INVENTORY\.md' README.md || fail "README must link the data-flow inventory"
rg -q 'SECURITY\.md' README.md || fail "README must link the private security-reporting policy"
rg -q 'Codex `/hooks`' README.md || fail "README must distinguish Codex config from Hook trust"

require_documented 'security/advisories/new' SECURITY.md "Private GitHub advisory channel"
require_documented 'Do not include API keys' SECURITY.md "Secret-safe reporting guidance"

echo "Legal and data-flow invariants: PASS"
